spring:
  application:
    name: config-server
  profiles:
    active:
    - native, git # tells Spring Cloud Config, you'll read the config data from a git repo ('native' if we need to reed from file system)
  cloud:
    config:
      server: # Local configuration: This location can either of classpath or locations in the filesystem
        native: # Reads from a specific filesystem folder
          #          search-locations: file:////home/ahmedabdelnaby # search location where the configuration files are stored
          search-locations: classpath:/config # if we need to specify a root directory (resources/config/) for many config files
        git:
          default-label: master # the branch name for the below repo
          uri: https://github.com/ihuaylupo/config.git
          searchPaths: licensing-service
server:
  port: 8071